apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # expõe para fora do cluster
  selector:
    app: nginx  # conecta com o deployment pelo label
  ports:
    - protocol: TCP
      port: 80          # porta interna do service (padrão nginx)
      targetPort: 80    # porta do container nginx
      nodePort: 30080   # porta externa no node (você pode escolher 30000-32767)
